language: php

php:
  - 7.2

services:
  - mysql

before_script:
  ## Packages
  - sudo apt-get -qq update > /dev/null
  ## Composer
  - travis_retry composer self-update
  - travis_retry composer install
  - mysql -e 'CREATE DATABASE indique;'
  - mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'datascan';"

script: 
  - php vendor/jorgegru/migrate/start init
  - php vendor/jorgegru/migrate/start migrate
  - mysql -u root --password="datascan" < tests/travis.sql
  - ./vendor/bin/phpunit --configuration ./travis.phpunit.xml.dist

notifications:
  email: false