language: php

php:
  - 7.2

services:
  - mysql

before_script:
  ## Packages
  - sudo apt-get -qq update > /dev/null
  ## Composer
  - travis_retry composer self-update
  - travis_retry composer install
  - mysql -e 'CREATE DATABASE indique;'
  - cp .env.example .env

script: composer test

notifications:
  email: false