language: php

php:
  - 7.2

services:
  - mysql

before_script:
  ## Packages
  - sudo apt-get -qq update > /dev/null
  ## Composer
  - travis_retry composer self-update
  - travis_retry composer install
  - mysql -e 'CREATE DATABASE indique;'
  - ALTER USER 'root'@'localhost' IDENTIFIED BY 'datascan';'

script: 
  - ./vender/bin/phpunit

notifications:
  email: false