language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2


before_script:
  ## Packages
  - sudo apt-get -qq update > /dev/null
  ## Composer
  - travis_retry composer self-update
  - travis_retry composer install

script: vendor/bin/phpunit

notifications:
  email: false